# Generated by Django 3.1.2 on 2021-12-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='select',
            field=models.IntegerField(default=0),
        ),
    ]
