# Generated by Django 3.1.2 on 2021-12-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(verbose_name='lng')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
    ]
